# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 433)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.device = QtWidgets.QGroupBox(self.groupBox)
        self.device.setMinimumSize(QtCore.QSize(0, 0))
        self.device.setMaximumSize(QtCore.QSize(200, 16777215))
        self.device.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.device.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.device.setObjectName("device")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.device)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Eqlist = QtWidgets.QListWidget(self.device)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Eqlist.sizePolicy().hasHeightForWidth())
        self.Eqlist.setSizePolicy(sizePolicy)
        self.Eqlist.setMinimumSize(QtCore.QSize(0, 70))
        self.Eqlist.setMaximumSize(QtCore.QSize(300, 200))
        self.Eqlist.setTabletTracking(False)
        self.Eqlist.setFrameShape(QtWidgets.QFrame.Box)
        self.Eqlist.setLineWidth(1)
        self.Eqlist.setMidLineWidth(0)
        self.Eqlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Eqlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Eqlist.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Eqlist.setAutoScrollMargin(1)
        self.Eqlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Eqlist.setTabKeyNavigation(True)
        self.Eqlist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Eqlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.Eqlist.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.Eqlist.setMovement(QtWidgets.QListView.Static)
        self.Eqlist.setFlow(QtWidgets.QListView.TopToBottom)
        self.Eqlist.setProperty("isWrapping", False)
        self.Eqlist.setResizeMode(QtWidgets.QListView.Adjust)
        self.Eqlist.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.Eqlist.setViewMode(QtWidgets.QListView.ListMode)
        self.Eqlist.setModelColumn(0)
        self.Eqlist.setUniformItemSizes(False)
        self.Eqlist.setSelectionRectVisible(False)
        self.Eqlist.setObjectName("Eqlist")
        self.verticalLayout_4.addWidget(self.Eqlist)
        self.RefreshBtn = QtWidgets.QPushButton(self.device)
        self.RefreshBtn.setObjectName("RefreshBtn")
        self.verticalLayout_4.addWidget(self.RefreshBtn)
        self.gridLayout.addWidget(self.device, 0, 1, 1, 1)
        self.LiZhi = QtWidgets.QGroupBox(self.groupBox)
        self.LiZhi.setObjectName("LiZhi")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LiZhi)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yaoji = QtWidgets.QRadioButton(self.LiZhi)
        self.yaoji.setEnabled(True)
        self.yaoji.setObjectName("yaoji")
        self.verticalLayout_2.addWidget(self.yaoji)
        self.yuanshi = QtWidgets.QRadioButton(self.LiZhi)
        self.yuanshi.setEnabled(True)
        self.yuanshi.setObjectName("yuanshi")
        self.verticalLayout_2.addWidget(self.yuanshi)
        self.buhuifu = QtWidgets.QRadioButton(self.LiZhi)
        self.buhuifu.setChecked(True)
        self.buhuifu.setObjectName("buhuifu")
        self.verticalLayout_2.addWidget(self.buhuifu)
        self.gridLayout.addWidget(self.LiZhi, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.MissionTree = QtWidgets.QTreeWidget(self.groupBox_2)
        self.MissionTree.setMinimumSize(QtCore.QSize(0, 70))
        self.MissionTree.setObjectName("MissionTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.MissionTree)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.MissionTree)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.verticalLayout_5.addWidget(self.MissionTree)
        self.SelfMission = QtWidgets.QCheckBox(self.groupBox_2)
        self.SelfMission.setObjectName("SelfMission")
        self.verticalLayout_5.addWidget(self.SelfMission)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buxianzhi = QtWidgets.QCheckBox(self.groupBox_6)
        self.buxianzhi.setMaximumSize(QtCore.QSize(60, 16777215))
        self.buxianzhi.setObjectName("buxianzhi")
        self.horizontalLayout_3.addWidget(self.buxianzhi)
        self.Times = QtWidgets.QSpinBox(self.groupBox_6)
        self.Times.setMinimum(1)
        self.Times.setMaximum(999)
        self.Times.setObjectName("Times")
        self.horizontalLayout_3.addWidget(self.Times)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkThree = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkThree.setMaximumSize(QtCore.QSize(117, 16777215))
        self.checkThree.setObjectName("checkThree")
        self.horizontalLayout_4.addWidget(self.checkThree)
        self.threeTimes = QtWidgets.QSpinBox(self.groupBox_5)
        self.threeTimes.setEnabled(True)
        self.threeTimes.setMinimum(1)
        self.threeTimes.setMaximum(999)
        self.threeTimes.setObjectName("threeTimes")
        self.horizontalLayout_4.addWidget(self.threeTimes)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LogText = QtWidgets.QTextBrowser(self.groupBox_4)
        self.LogText.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LogText.setFont(font)
        self.LogText.setReadOnly(True)
        self.LogText.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.LogText.setOpenExternalLinks(True)
        self.LogText.setObjectName("LogText")
        self.verticalLayout_3.addWidget(self.LogText)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RunBtn = QtWidgets.QPushButton(self.frame_7)
        self.RunBtn.setObjectName("RunBtn")
        self.horizontalLayout.addWidget(self.RunBtn)
        self.EndButon = QtWidgets.QPushButton(self.frame_7)
        self.EndButon.setObjectName("EndButon")
        self.horizontalLayout.addWidget(self.EndButon)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.disp_btn = QtWidgets.QPushButton(self.frame)
        self.disp_btn.setObjectName("disp_btn")
        self.horizontalLayout_5.addWidget(self.disp_btn)
        self.ClearLogBtn = QtWidgets.QPushButton(self.frame)
        self.ClearLogBtn.setObjectName("ClearLogBtn")
        self.horizontalLayout_5.addWidget(self.ClearLogBtn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.Eqlist.setCurrentRow(-1)
        self.ClearLogBtn.clicked.connect(self.LogText.clear)
        self.buxianzhi.toggled['bool'].connect(self.Times.setDisabled)
        self.SelfMission.toggled['bool'].connect(self.MissionTree.setDisabled)
        self.checkThree.toggled['bool'].connect(self.threeTimes.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.RunBtn, self.LogText)
        Form.setTabOrder(self.LogText, self.EndButon)
        Form.setTabOrder(self.EndButon, self.yaoji)
        Form.setTabOrder(self.yaoji, self.yuanshi)
        Form.setTabOrder(self.yuanshi, self.buhuifu)
        Form.setTabOrder(self.buhuifu, self.Eqlist)
        Form.setTabOrder(self.Eqlist, self.RefreshBtn)
        Form.setTabOrder(self.RefreshBtn, self.MissionTree)
        Form.setTabOrder(self.MissionTree, self.SelfMission)
        Form.setTabOrder(self.SelfMission, self.Times)
        Form.setTabOrder(self.Times, self.buxianzhi)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "基础设置"))
        self.device.setTitle(_translate("Form", "设备选择"))
        self.Eqlist.setSortingEnabled(False)
        self.RefreshBtn.setText(_translate("Form", "刷新设备"))
        self.LiZhi.setTitle(_translate("Form", "恢复理智"))
        self.yaoji.setText(_translate("Form", "药剂恢复"))
        self.yuanshi.setText(_translate("Form", "至纯原石恢复"))
        self.buhuifu.setText(_translate("Form", "不恢复"))
        self.groupBox_2.setTitle(_translate("Form", "关卡选择"))
        self.MissionTree.headerItem().setText(0, _translate("Form", "关卡"))
        __sortingEnabled = self.MissionTree.isSortingEnabled()
        self.MissionTree.setSortingEnabled(False)
        self.MissionTree.topLevelItem(0).setText(0, _translate("Form", "材料本"))
        self.MissionTree.topLevelItem(0).child(0).setText(0, _translate("Form", "龙门币"))
        self.MissionTree.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "CE-1"))
        self.MissionTree.topLevelItem(0).child(0).child(1).setText(0, _translate("Form", "CE-2"))
        self.MissionTree.topLevelItem(0).child(0).child(2).setText(0, _translate("Form", "CE-3"))
        self.MissionTree.topLevelItem(0).child(0).child(3).setText(0, _translate("Form", "CE-4"))
        self.MissionTree.topLevelItem(0).child(0).child(4).setText(0, _translate("Form", "CE-5"))
        self.MissionTree.topLevelItem(0).child(1).setText(0, _translate("Form", "经验本"))
        self.MissionTree.topLevelItem(0).child(1).child(0).setText(0, _translate("Form", "LS-1"))
        self.MissionTree.topLevelItem(0).child(1).child(1).setText(0, _translate("Form", "LS-2"))
        self.MissionTree.topLevelItem(0).child(1).child(2).setText(0, _translate("Form", "LS-3"))
        self.MissionTree.topLevelItem(0).child(1).child(3).setText(0, _translate("Form", "LS-4"))
        self.MissionTree.topLevelItem(0).child(1).child(4).setText(0, _translate("Form", "LS-5"))
        self.MissionTree.topLevelItem(0).child(2).setText(0, _translate("Form", "碳素组"))
        self.MissionTree.topLevelItem(0).child(2).child(0).setText(0, _translate("Form", "SK-1"))
        self.MissionTree.topLevelItem(0).child(2).child(1).setText(0, _translate("Form", "SK-2"))
        self.MissionTree.topLevelItem(0).child(2).child(2).setText(0, _translate("Form", "SK-3"))
        self.MissionTree.topLevelItem(0).child(2).child(3).setText(0, _translate("Form", "SK-4"))
        self.MissionTree.topLevelItem(0).child(2).child(4).setText(0, _translate("Form", "SK-5"))
        self.MissionTree.topLevelItem(0).child(3).setText(0, _translate("Form", "技能书"))
        self.MissionTree.topLevelItem(0).child(3).child(0).setText(0, _translate("Form", "CA-1"))
        self.MissionTree.topLevelItem(0).child(3).child(1).setText(0, _translate("Form", "CA-2"))
        self.MissionTree.topLevelItem(0).child(3).child(2).setText(0, _translate("Form", "CA-3"))
        self.MissionTree.topLevelItem(0).child(3).child(3).setText(0, _translate("Form", "CA-4"))
        self.MissionTree.topLevelItem(0).child(3).child(4).setText(0, _translate("Form", "CA-5"))
        self.MissionTree.topLevelItem(0).child(4).setText(0, _translate("Form", "采购证"))
        self.MissionTree.topLevelItem(0).child(4).child(0).setText(0, _translate("Form", "AP-1"))
        self.MissionTree.topLevelItem(0).child(4).child(1).setText(0, _translate("Form", "AP-2"))
        self.MissionTree.topLevelItem(0).child(4).child(2).setText(0, _translate("Form", "AP-3"))
        self.MissionTree.topLevelItem(0).child(4).child(3).setText(0, _translate("Form", "AP-4"))
        self.MissionTree.topLevelItem(0).child(4).child(4).setText(0, _translate("Form", "AP-5"))
        self.MissionTree.topLevelItem(1).setText(0, _translate("Form", "精英"))
        self.MissionTree.topLevelItem(1).child(0).setText(0, _translate("Form", "医疗/重装"))
        self.MissionTree.topLevelItem(1).child(0).child(0).setText(0, _translate("Form", "PR-A-1"))
        self.MissionTree.topLevelItem(1).child(0).child(1).setText(0, _translate("Form", "PR-A-2"))
        self.MissionTree.topLevelItem(1).child(1).setText(0, _translate("Form", "术士/狙击"))
        self.MissionTree.topLevelItem(1).child(1).child(0).setText(0, _translate("Form", "PR-B-1"))
        self.MissionTree.topLevelItem(1).child(1).child(1).setText(0, _translate("Form", "PR-B-2"))
        self.MissionTree.topLevelItem(1).child(2).setText(0, _translate("Form", "先锋/辅助"))
        self.MissionTree.topLevelItem(1).child(2).child(0).setText(0, _translate("Form", "PR-C-1"))
        self.MissionTree.topLevelItem(1).child(2).child(1).setText(0, _translate("Form", "PR-C-2"))
        self.MissionTree.topLevelItem(1).child(3).setText(0, _translate("Form", "近卫/特种"))
        self.MissionTree.topLevelItem(1).child(3).child(0).setText(0, _translate("Form", "PR-D-1"))
        self.MissionTree.topLevelItem(1).child(3).child(1).setText(0, _translate("Form", "PR-D-2"))
        self.MissionTree.setSortingEnabled(__sortingEnabled)
        self.SelfMission.setText(_translate("Form", "自己指定当前关卡"))
        self.groupBox_3.setTitle(_translate("Form", "高级设置"))
        self.groupBox_6.setTitle(_translate("Form", "运行次数限制"))
        self.buxianzhi.setText(_translate("Form", "不限制"))
        self.groupBox_5.setTitle(_translate("Form", "非三星次数限制"))
        self.checkThree.setText(_translate("Form", "不限制"))
        self.groupBox_4.setTitle(_translate("Form", "运行日志"))
        self.RunBtn.setText(_translate("Form", "运行"))
        self.EndButon.setText(_translate("Form", "结束运行"))
        self.disp_btn.setText(_translate("Form", "显示界面"))
        self.ClearLogBtn.setText(_translate("Form", "清除日志"))
