# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTab.setObjectName("MainTab")
        self.verticalLayout.addWidget(self.MainTab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menu_5)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menu_5)
        self.menu_7.setObjectName("menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.CreateTab = QtWidgets.QAction(MainWindow)
        self.CreateTab.setObjectName("CreateTab")
        self.DeleteTab = QtWidgets.QAction(MainWindow)
        self.DeleteTab.setObjectName("DeleteTab")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.Scan = QtWidgets.QAction(MainWindow)
        self.Scan.setObjectName("Scan")
        self.DeleteAllLog = QtWidgets.QAction(MainWindow)
        self.DeleteAllLog.setObjectName("DeleteAllLog")
        self.Soft = QtWidgets.QAction(MainWindow)
        self.Soft.setObjectName("Soft")
        self.Author = QtWidgets.QAction(MainWindow)
        self.Author.setObjectName("Author")
        self.Help = QtWidgets.QAction(MainWindow)
        self.Help.setObjectName("Help")
        self.UnScan = QtWidgets.QAction(MainWindow)
        self.UnScan.setObjectName("UnScan")
        self.RemoteScan = QtWidgets.QAction(MainWindow)
        self.RemoteScan.setObjectName("RemoteScan")
        self.login_ID = QtWidgets.QAction(MainWindow)
        self.login_ID.setObjectName("login_ID")
        self.delconfig = QtWidgets.QAction(MainWindow)
        self.delconfig.setObjectName("delconfig")
        self.report = QtWidgets.QAction(MainWindow)
        self.report.setObjectName("report")
        self.add_report = QtWidgets.QAction(MainWindow)
        self.add_report.setObjectName("add_report")
        self.plan = QtWidgets.QAction(MainWindow)
        self.plan.setObjectName("plan")
        self.add_plan = QtWidgets.QAction(MainWindow)
        self.add_plan.setObjectName("add_plan")
        self.menu.addAction(self.CreateTab)
        self.menu.addAction(self.DeleteTab)
        self.menu.addSeparator()
        self.menu.addAction(self.Exit)
        self.menu_2.addAction(self.Scan)
        self.menu_2.addAction(self.RemoteScan)
        self.menu_2.addAction(self.UnScan)
        self.menu_3.addAction(self.DeleteAllLog)
        self.menu_4.addAction(self.Soft)
        self.menu_4.addAction(self.Author)
        self.menu_4.addAction(self.Help)
        self.menu_6.addAction(self.report)
        self.menu_6.addAction(self.add_report)
        self.menu_7.addAction(self.plan)
        self.menu_7.addAction(self.add_plan)
        self.menu_5.addAction(self.login_ID)
        self.menu_5.addAction(self.delconfig)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.menu_6.menuAction())
        self.menu_5.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.retranslateUi(MainWindow)
        self.MainTab.setCurrentIndex(-1)
        self.Exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoArknight v1.2.2"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "设备"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.menu_5.setTitle(_translate("MainWindow", "企鹅物流数据统计"))
        self.menu_6.setTitle(_translate("MainWindow", "上报数据"))
        self.menu_7.setTitle(_translate("MainWindow", "计算规划"))
        self.CreateTab.setText(_translate("MainWindow", "新建"))
        self.CreateTab.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.DeleteTab.setText(_translate("MainWindow", "删除"))
        self.DeleteTab.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.Exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.Scan.setText(_translate("MainWindow", "扫描本地模拟器"))
        self.Scan.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.DeleteAllLog.setText(_translate("MainWindow", "删除所有日志文件"))
        self.DeleteAllLog.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.Soft.setText(_translate("MainWindow", "关于软件"))
        self.Author.setText(_translate("MainWindow", "关于作者"))
        self.Help.setText(_translate("MainWindow", "帮助"))
        self.UnScan.setText(_translate("MainWindow", "删除扫描结果"))
        self.RemoteScan.setText(_translate("MainWindow", "远程扫描"))
        self.login_ID.setText(_translate("MainWindow", "登入ID"))
        self.delconfig.setText(_translate("MainWindow", "删除设置"))
        self.report.setText(_translate("MainWindow", "上报"))
        self.add_report.setText(_translate("MainWindow", "添加数据"))
        self.plan.setText(_translate("MainWindow", "计算"))
        self.add_plan.setText(_translate("MainWindow", "添加数据"))
